project:
  type: website

website:
  title: "Brain Atrophy Genetics"
  navbar:
    left:
      - href: index.qmd
        text: Overview

format:
  html:
    theme: journal
    css: styles.css
    toc: true